### ISSUE TITLE
Confused by this idiom: tap(...) -> subscribe()

### ISSUE THREAD

**Issue by paulreimer** [kirkshoop/twitter#9]
For example, here:
https://github.com/kirkshoop/twitter/blob/6654b267a12184847e3a5b7cbf2eddd230ac6e29/rxcurl.h#L71-L78

Any reason this is different (preferred?) from just a single `subscribe` instead of the `tap | subscribe`?

**Comment by kirkshoop** [comment]
Hi!

I prefer to use tap consistently to create side effects rather than put some in `tap` and some in `subscribe`. there are times when a side effect needs to be placed in an expression that does not have a `subscribe` or between two operators. Always using `tap` for side effects makes them stand out.

**Comment by paulreimer** [comment]
OK that makes sense. So it's a convention thing to use `tap`, but it would technically work in `subscribe` as well. Just making sure I got it! (Also is that personal preference or is there a RX "Best Practices" guide or someth. somewhere?)

**Comment by kirkshoop** [comment]
I will claim this as a personal preference :) 

I know that @staltz has mentioned style opinions for RxJS in the past, but I don't know of any official style guides.
